import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, chmod, rm, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { maintain, maintenanceArguments, maintenanceEnvironment } from "./refresh-host.ts";

const request = {
  profile: "work" as const,
  action: "list" as const,
  argument: "",
  url: "http://127.0.0.1:48886",
  dataDir: "/Users/test/.bb-work",
  cliPath: "/official/bb",
};

void test("maintenance keeps account context on the selected machine", () => {
  const inherited = {
    BB_SERVER_URL: "https://personal.example",
    BB_HOST_DAEMON_PORT: "3000",
    BB_THREAD_ID: "parent",
    BB_SERVER_HEADERS: "private",
    PATH: "/bin",
  };

  const env = maintenanceEnvironment(request, inherited);
  assert.equal(env.BB_DATA_DIR, "/Users/test/.bb-work");
  assert.equal(env.BB_SERVER_URL, request.url);
  assert.equal(env.BB_THREAD_ID, undefined);
  assert.equal(env.BB_HOST_DAEMON_PORT, undefined);
  assert.equal(env.BB_SERVER_HEADERS, undefined);
  assert.equal(env.PATH, "/bin");
  assert.equal(inherited.BB_SERVER_URL, "https://personal.example");
});

void test("maintenance rejects remote URLs and arbitrary commands", () => {
  for (const url of [
    "https://work.example",
    "http://user:pass@localhost",
    "http://localhost/path",
    "file:///tmp/a",
  ])
    assert.throws(() => maintenanceEnvironment({ ...request, url }));

  for (const action of ["remove", "update", "exec", "login"])
    assert.throws(() => maintenanceArguments(action, "profiles"));
  assert.throws(() => maintenanceArguments("reload", "--all"));
  assert.throws(() => maintenanceArguments("build", "relative"));
  assert.deepEqual(maintenanceArguments("install", "/source with spaces/plugin"), [
    "plugin",
    "install",
    "path:/source with spaces/plugin",
    "--yes",
  ]);
});

void test("host maintenance verifies the target directory before plugin commands", async () => {
  const root = await mkdtemp(join(tmpdir(), "profiles-identity-"));

  try {
    const actual = join(root, ".bb");
    const expected = join(root, ".bb-work");
    const marker = join(root, "called");
    const cli = join(root, "bb");
    await mkdir(actual);
    await mkdir(expected);
    // Test paths are generated by mkdtemp; JSON literals are consumed only by JavaScript.
    await writeFile(
      cli,
      `#!/usr/bin/env node\nif(process.argv[2]==='status')console.log(JSON.stringify({dataDir:${JSON.stringify(actual)}}));else {require('fs').writeFileSync(${JSON.stringify(marker)},'called');console.log('{"plugins":[]}');}\n`,
    );
    await chmod(cli, 0o700);
    await assert.rejects(maintain({ ...request, cliPath: cli, dataDir: expected }));
    await assert.rejects(access(marker));
    assert.deepEqual(JSON.parse(await maintain({ ...request, cliPath: cli, dataDir: actual })), {
      plugins: [],
    });
    await access(marker);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
