import type { PluginSidebarThread } from "@get-bb/plugin-sdk/app";

export const thread: PluginSidebarThread = {
  id: "one",
  projectId: "project",
  title: "Reminder",
  titleFallback: null,
  displayTitle: "Reminder",
  lifecycleOwnerThreadId: null,
  sourceThreadId: null,
  status: "idle",
  runtimeStatus: "idle",
  queuedWork: "none",
  pinnedAt: null,
  pinSortKey: null,
  archivedAt: null,
  href: "/projects/project/threads/one",
  isHidden: false,
  parentThreadId: null,
  sectionId: null,
  originKind: null,
  originPluginId: null,
  providerId: "codex",
  hasPendingInteraction: false,
  activity: { workflows: 0, backgroundAgents: 0, backgroundCommands: 0, planMode: 0, goals: 0 },
  indicator: "none",
  indicatorLabel: null,
  isUnread: false,
  isPinned: false,
  isArchived: false,
  environment: null,
  host: null,
  createdAt: 0,
  updatedAt: 0,
  lastReadAt: 0,
  latestAttentionAt: 0,
};
